# Generated by Django 4.2.1 on 2023-11-21 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_productcategory_elected_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='elected_books',
            new_name='selected_books',
        ),
    ]
