# Generated by Django 4.2.1 on 2023-11-22 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_rename_elected_books_productcategory_selected_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='selected_books',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='product_module.productcategory', verbose_name='دسته بندی'),
            preserve_default=False,
        ),
    ]
