# Generated by Django 4.2.1 on 2023-11-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_remove_productcategory_selected_books_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(db_index=True, related_name='product_categories', to='product_module.productcategory', verbose_name='دسته بندی'),
        ),
    ]
