# Generated by Django 4.2.1 on 2023-11-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/product_category', verbose_name='تصویر'),
        ),
    ]
