# Generated by Django 4.2.1 on 2023-11-25 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0010_productcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_time_free',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.CharField(choices=[('10', '10'), ('20', '20 '), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], max_length=3, verbose_name='درصد')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('dead_line', models.DateTimeField(null=True, verbose_name='تاریخ اتمام')),
                ('product', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='اسم محصول')),
            ],
        ),
    ]
