# Generated by Django 4.2.7 on 2023-11-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='short_description',
        ),
    ]
