# Generated by Django 4.2.7 on 2023-11-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0002_remove_article_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='توضیحات کوتاه'),
        ),
    ]
