# Generated by Django 4.2.7 on 2023-11-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
    ]
