# Generated by Django 4.2.7 on 2023-11-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
    ]
