# Generated by Django 4.2.7 on 2023-11-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='image/profile', verbose_name='آواتار'),
        ),
    ]
