# Generated by Django 4.2.7 on 2023-11-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=100, verbose_name='نام سایت')),
                ('link', models.CharField(max_length=100, verbose_name='لینک')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس')),
                ('phone', models.IntegerField(verbose_name='شماره تماس')),
                ('email', models.CharField(max_length=100, verbose_name='ایمیل')),
                ('fax', models.CharField(max_length=100, verbose_name='فکس')),
                ('copy_right', models.CharField(max_length=200, verbose_name='متن کپی رایت')),
                ('about_us', models.TextField(verbose_name='درباره سایت')),
                ('about_us_text', models.TextField(verbose_name='متن هدف سایت')),
                ('logo', models.ImageField(upload_to='image', verbose_name='تصویر لوگو')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
