# Generated by Django 4.2.7 on 2023-11-10 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0002_sitesetting_is_active_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinkBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی لینک فوتر',
                'verbose_name_plural': 'دسته بندی لینک های فوتر',
            },
        ),
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url', models.URLField(blank=True, max_length=300, null=True, verbose_name='لینک')),
                ('image', models.ImageField(upload_to='images/banner', verbose_name='تصویر بنر')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال')),
                ('position', models.CharField(choices=[('product_list', 'صفحه لیست محصولات'), ('product_detail', 'صفحه توضیحات محصولات'), ('about_us', 'درباره ما'), ('contact_us', 'تماس با ما')], max_length=250, verbose_name='جایگاه نمایش')),
            ],
            options={
                'verbose_name': 'بنر سایت',
                'verbose_name_plural': 'بنر های سایت',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url_title', models.CharField(max_length=100, verbose_name='عنوان در url')),
                ('link', models.URLField(max_length=100, verbose_name='لینک')),
                ('image', models.ImageField(upload_to='image/slider', verbose_name='تصویر اسلایدر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'اسلایدر سایت',
                'verbose_name_plural': 'اسلایدر های سایت',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url_title', models.CharField(max_length=100, verbose_name='عنوان در url')),
                ('footer_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_setting.footerlinkbox', verbose_name='لینک فوتر')),
            ],
            options={
                'verbose_name': 'لینک فوتر',
                'verbose_name_plural': 'لینک های فوتر',
            },
        ),
    ]
