# Generated by Django 4.2.7 on 2023-11-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0003_footerlinkbox_sitebanner_slider_footerlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='url_title',
            field=models.CharField(max_length=100, verbose_name='لینک'),
        ),
    ]
