# Generated by Django 4.2.7 on 2023-11-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0004_alter_footerlink_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='position',
            field=models.CharField(choices=[('product_list', 'صفحه لیست محصولات'), ('product_detail', 'صفحه توضیحات محصولات'), ('contact_us', 'تماس با ما'), ('article_list', 'لیست مقالات')], max_length=250, verbose_name='جایگاه نمایش'),
        ),
    ]
